apiVersion: v1
kind: Pod
metadata:
  name: nginx #pod name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx #name of conatiner
    image: nginx


